from sqlalchemy import func, select

from src.models.chi_tiet_don_mua import ChiTietDonMua
from src.models.don_mua_nguyen_lieu import DonMuaNguyenLieu
from src.models.nguyen_lieu_model import NguyenLieu
from src.models.nguyen_lieu_nha_cung_cap_model import NguyenLieuNhaCungCap
from src.models.nha_cung_cap_model import NhaCungCap


class DonMuaRepository:
    @staticmethod
    def list(db, search=None, ma_ncc=None, trang_thai=None, ngay_dat_tu=None, ngay_dat_den=None):
        query = select(DonMuaNguyenLieu, NhaCungCap.ten_ncc).join(NhaCungCap)
        if search and search.strip():
            term = search.strip().replace("/", "//").replace("%", "/%").replace("_", "/_")
            query = query.where(DonMuaNguyenLieu.ma_don_mua.ilike(f"%{term}%", escape="/"))
        for column, value in ((DonMuaNguyenLieu.ma_ncc, ma_ncc), (DonMuaNguyenLieu.trang_thai, trang_thai)):
            if value is not None:
                query = query.where(column == value)
        if ngay_dat_tu is not None:
            query = query.where(DonMuaNguyenLieu.ngay_dat_hang >= ngay_dat_tu)
        if ngay_dat_den is not None:
            query = query.where(DonMuaNguyenLieu.ngay_dat_hang <= ngay_dat_den)
        return db.execute(query.order_by(DonMuaNguyenLieu.ma_don_mua)).all()

    @staticmethod
    def get(db, code, lock=False):
        query = select(DonMuaNguyenLieu).where(DonMuaNguyenLieu.ma_don_mua == code)
        if lock:
            query = query.with_for_update().execution_options(populate_existing=True)
        return db.scalar(query)

    @staticmethod
    def current_date(db):
        return db.scalar(select(func.current_date()))

    @staticmethod
    def current_timestamp(db):
        return db.scalar(select(func.current_timestamp()))

    @staticmethod
    def update_workflow(db, model, values):
        for key, value in values.items():
            setattr(model, key, value)
        db.flush()
        db.refresh(model)
        return model

    @staticmethod
    def orders_for_proposal(db, proposal_code):
        return list(db.scalars(select(DonMuaNguyenLieu).where(
            DonMuaNguyenLieu.ma_de_xuat == proposal_code
        ).order_by(DonMuaNguyenLieu.ma_ncc)))

    @staticmethod
    def supplier(db, code, lock=False):
        query = select(NhaCungCap).where(NhaCungCap.ma_ncc == code)
        if lock:
            query = query.with_for_update(read=True).execution_options(populate_existing=True)
        return db.scalar(query)

    @staticmethod
    def materials(db, codes):
        return db.scalars(select(NguyenLieu).where(NguyenLieu.ma_nguyen_lieu.in_(codes))
                          .order_by(NguyenLieu.ma_nguyen_lieu).with_for_update(read=True)).all()

    @staticmethod
    def mappings(db, supplier, codes):
        return db.scalars(select(NguyenLieuNhaCungCap).where(
            NguyenLieuNhaCungCap.ma_ncc == supplier,
            NguyenLieuNhaCungCap.ma_nguyen_lieu.in_(codes),
        ).order_by(NguyenLieuNhaCungCap.ma_nguyen_lieu).with_for_update(read=True)
          .execution_options(populate_existing=True)).all()

    @staticmethod
    def details(db, code):
        return db.execute(select(ChiTietDonMua, NguyenLieu).join(NguyenLieu).where(
            ChiTietDonMua.ma_don_mua == code
        ).order_by(ChiTietDonMua.ma_nguyen_lieu)).all()

    @staticmethod
    def receipt_details(db, code):
        return list(db.scalars(select(ChiTietDonMua).where(
            ChiTietDonMua.ma_don_mua == code
        ).order_by(ChiTietDonMua.ma_chi_tiet_don_mua).with_for_update()
          .execution_options(populate_existing=True)))

    @staticmethod
    def update_receipt_detail(db, model, quantity, reason):
        model.so_luong_thuc_nhan = quantity
        model.ly_do_khong_nhan = reason
        db.flush()

    @staticmethod
    def create(db, values):
        model = DonMuaNguyenLieu(**values)
        db.add(model)
        db.flush()  # INSERT RETURNING fetches the code generated by PostgreSQL.
        return model

    @staticmethod
    def replace_details(db, code, items):
        existing = {row.ma_nguyen_lieu: row for row in db.scalars(select(ChiTietDonMua).where(
            ChiTietDonMua.ma_don_mua == code
        ))}
        desired = {item["ma_nguyen_lieu"]: item for item in items}
        for material, row in existing.items():
            if material not in desired:
                db.delete(row)  # Only remove obsolete lines of an editable order.
        for material, values in desired.items():
            row = existing.get(material)
            if row is None:
                row = ChiTietDonMua(ma_don_mua=code, **values)
                db.add(row)
            else:
                for key, value in values.items():
                    setattr(row, key, value)
        db.flush()
